<<<<<<< HEAD
Title: Sedat Touray
logo: "/images/20201028_061725.jpg?raw=True" # your photo (or logo) here
=======
title: Sedat Touray
logo: "/images/IMG_0525.JPG?raw=True" # your photo (or logo) here
>>>>>>> 1fc0b984bdc90c10a496290e53b7797f0f2bc425
description: > # your text below (remove <br> elements if you don't need line breaks)
  Rising Senior at the University of Rhode Island
 <br> <br>
  Department of Computer Science and Statistics
  <br> <br>
  <a href="https://https://www.linkedin.com/in/sedat-touray-138443100//">View My LinkedIn Profile</a> 
  <br> <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
